# This is a basic workflow to help you get started with Actions

name: LJS Azure Resume CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.LJS_AZURE_RESUME }}
          
- name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ljsstore01 -d '$web' -s .            
- name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "ljscdnpro1" --name "ljscdnpoint1" --resource-group "LJSResumeCh"
# Azure logout 
    - name: logout
      run: |
            az logout
            
